[package]
name = "axum-test-helper"
version = "0.1.0"
edition = "2021"
categories = ["axum", "test", "web-testing"]
description = "Extra utilities for axum"
homepage = "https://github.com/cloudwalk/axum-test-helper"
keywords = ["axum", "test", "test-framework"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cloudwalk/axum-test-helper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
reqwest = { version = "0.11", features = ["json", "stream", "multipart"] }
http = "0.2.5"
http-body = "0.4.4"
bytes = "1.0"
tower = "0.4.11"
tower-service = "0.3"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1" }
hyper = "0.14.14"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
